### ISSUE TITLE
What to use for viruses in groups.yaml?

### ISSUE THREAD

**Issue by Ben7124** [GDKO/AvP#27]
Hello,
Thanks for creating this great tool.
I have a question about detecting hgt from donors in other kingdoms to viruses. I have a file of proteins from different kinds of viruses and I am wondering how to set up my groups.yaml file. I know what to put for Ingroup, but I am not sure what to put for EGP since I have proteins from different types of viruses in my file. Could EGP be the taxid (2080735) for DNA viruses since my proteins are from DNA viruses and to exclude this from calculations? Thank you for your help.

Ingroup:
 10239: Viruses
EGP:
 ?: ? # don't know what to fill in here

**Comment by GDKO** [comment]
Hi @Ben7124,

Yes, that would do. 

Cheers,
Georgios

**Comment by GDKO** [comment]
Hi @Ben7124,

Now that I think about it, I don't know if taxid 2080735 is used in the taxonomic lineages for viruses. Check one taxid of your protein set and see if it is part of the full lineage. If not, you can set EGP to be the same as Ingroup and that will exclude all viruses from the calculation.

Cheers,
Georgios

**Comment by Ben7124** [comment]
Thank you for your quick response! When I set EGP the same as Ingroup (10239), the results all say "HGT-NT". **Is that a valid result when compared to "HGT and phylogenetic tree supports the hypothesis"?** 

And you are correct in that taxid 2080735 is not part of the full lineage when I checked. 

I have around 1000 virus proteins that I want to run through AvP. I suppose one way is to run the pipeline and set EGP for each protein according to the lineage, but this may take an extremely long time. Any suggestions on how to tackle this will be greatly appreciated. Thank you again for your help!

**Comment by GDKO** [comment]
Hi @Ben7124,

Since all Ingroup sequences are excluded, the phylogenetic trees will always confirm the potential HGTs as HGT-NT (for the genes that pass the cutoffs specified in the config file). In this case, the phylogenetic trees can only be used for visualisation purposes and not to infer actual HGTs. However, depending on your question, looking at the trees can give you important information about your input data.

The ideal would be to group your proteins at family level (or any another taxonomic rank that makes sense to you) and run a separate analysis for each family, setting EGP to the family taxid.

Cheers,
Georgios

**Comment by Ben7124** [comment]
Thank you Georgios, that makes sense! I really appreciate your responses here and in helping people with your software. I will close the issue now.
