### ISSUE TITLE
diamond makeblastdb 

### ISSUE THREAD

**Issue by meisiy** [GDKO/AvP#28]
In the wiki, https://github.com/GDKO/AvP/wiki/Setting-up#Create-environment-with-conda

`diamond makedb --in uniprot_sprot.fasta.gz --taxonmap sp.taxids --db uniprot_sprot.fasta.dmnd --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp`
Terminal returns:
`Error: Invalid option: taxonnames`

In diamond v0.9.14.115, it seems we don't need the --taxonnames option.
`diamond makedb --in uniprot_sprot.fasta.gz --taxonmap sp.taxids --db uniprot_sprot.fasta.dmnd --taxonnodes taxdump/nodes.dmp`

Running was successful.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Remove the --taxonnames option from the diamond makedb command in the README.md file to fix the error mentioned in the GitHub issue.

You can review changes in this commit: https://github.com/lattaai12/GDKO-AvP-28/commit/ca6809c58b6f77fb90040901fa3f80365e4f1652.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by GDKO** [comment]
Hi @meisiy,

You are running a very old version of diamond. I would suggest upgrading to the newest version and running the commands as intended, as I cannot guarantee the downstream results.

Cheers,
Georgios

**Comment by meisiy** [comment]
> Hi @meisiy,
> 
> You are running a very old version of diamond. I would suggest upgrading to the newest version and running the commands as intended, as I cannot guarantee the downstream results.
> 
> Cheers, Georgios

Thank you Georgios for pointing out that, I updated Diamond to the latest version. And the running works.
FYI, it will download Diamond with an old version in Conda if we don't specify the version. That was what happened to me, maybe it will cause some confusion to people if they don't know.
